# Generated by Django 5.1 on 2024-09-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('Recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.TextField(default='No Description')),
                ('Cuisine', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50)),
                ('Diet', models.CharField(max_length=50)),
                ('Ingredients_name', models.TextField()),
                ('Ingredients_quantity', models.TextField()),
                ('Prep_time', models.IntegerField()),
                ('Cook_time', models.IntegerField()),
                ('Instructions', models.TextField()),
                ('Image_url', models.TextField()),
            ],
        ),
    ]
